# -*- makefile -*-

##-------------------##
##---]  TARGETS  [---##
##-------------------##
all:

add-chart:
	helm repo add onf https://charts.opencord.org
	helm repo update

clean:

help:
	@echo "Usage: make [options] [target] ..."
	@echo "Options:"
	@echo "  add-chart           Add default helm chart repo"
	@echo
	@echo '[CLEAN]'
	@echo '  clean               Remove generated content'

# [EOF]
