# -*- makefile -*-

repo := https://gerrit.opencord.org/plugins/gitiles/voltha-helm-charts/+/refs/heads/master


all:

#	https://gerrit.opencord.org/plugins/gitiles/voltha-helm-charts/+/refs/heads/master/bbsim/Chart.yaml
# ./bbsim/Chart.yaml
